version: '3.1'
services:
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "my_project"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "123"
    ports:
      - "33060:3306"