server:
  http:
    port: 8080

  static:
    enabled: true

  smart-server:
    application:
      name: "My Project"

  smart-routes:
    rewrite:
      - path: "/v1/{path}"
        to: "/{path}"

    cors:
      enabled: true
      always-allow-origin: true
      always-allow-credentials: true
      allowed-methods: ["GET", "POST", "PUT", "PATCH", "DELETE"]

  urouting:
    default-content-type: "application/json"
    content-type-priority: "CONFIG"

  auth:
    session-store: kikaha.caffeine.CaffeineSessionStore
#    session-id-manager: my.project.shared.infra.http.security.sessions.SessionManager
#    auth-mechanisms:
#      basic-authenticate: my.project.shared.infra.http.security.authentications.BasicAuthentication
#    identity-managers:
#      session-manager: my.project.shared.infra.http.security.authentications.BasicAuthentication
#    default-excluded-patterns: ["/api/internal/health-check"]
#    rules:
#      - pattern: "/v1/*"
#        auth-mechanisms:
#          - "basic-authenticate"
#        identity-managers:
#          - "session-manager"
#
#  db:
#    datasource-factory: my.project.shared.infra.database.jdbi.JDBIDatabase

  health-check:
    enabled: true
    url: "/api/internal/health-check"
